In [6]:
# Import the Libraries

import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

In [1]:
# Import the Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from scipy.special import inv_boxcox
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import scipy as sci
import scipy.stats as stats
from seaborn_qqplot import pplot
import sidetable

sns.set_style('whitegrid')
plt.style.use('ggplot')

import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# for HD visualizations
%config InlinrBackend.figure_format ='retina'

E:\Innomatics data sci\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
E:\Innomatics data sci\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
E:\Innomatics data sci\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [3]:
# request 

page = requests.get('https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=1')

In [3]:
page

In [4]:
soup = BeautifulSoup(page.text)

In [5]:
# Extracting all Data from Makaan webside
# this Extracting only first page

seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

# 1. Seller Name
seller_name = soup.find_all('a',class_='seller-name')
for i in seller_name:
    a = i.text
    seller.append(a)
    
# 2. Seller type
seller_type = soup.find_all('div',class_='second-line')
for i in seller_type:
    a = i.text
    sellertype.append(a)
    
# 3. BHK
BHK = soup.find_all('a',class_='typelink')
for i in BHK:
    a = i.text
    BHKs.append(a)
    
# 4. Location
loc = soup.find_all("a",class_="loclink")
for i in loc:
    a = i.text
    location.append(a)
    
# 5. City
city = soup.find_all("span",class_="cityName")
for i in city:
    a = i.text
    City.append(a)

# 6. Total Price
total_price = soup.find_all("td",class_="price")
for i in total_price:
    a = i.text
    Price.append(a)

# 7. price per sqft
price_per_sqft = soup.find_all("td",class_="lbl rate")
for i in price_per_sqft:
    a = i.text
    b = a.replace('/ sq ft','')
    Price_per_sqft.append(b)
    
# 8. Area in Sqft
Area_in_sqft = soup.find_all('td',class_='size')
for i in Area_in_sqft:
    a = i.text
    Area_sqft.append(a)
    
# 9. Construction status
cons_stus = soup.find_all('td',class_='val')
for i in cons_stus :
    a = i.text
    Cons_status.append(a)

In [6]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

20
20
20
20
20
20
20
20
20

In [7]:
# Create a DataFrame

Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [8]:
df1 = pd.DataFrame(Dictionary)
df1

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Shree Laxmi Venture,BUILDER,2 BHK Apartment,"Besa, Nagpur",Nagpur,35.31 L,"3,455",1022,Under Construction
1,Devprath Constructions LLP,BUILDER,2 BHK Apartment,"Parsodi, Nagpur",Nagpur,31.53 L,"3,500",901,Under Construction
2,Sirsikar Developers And Builders Pvt Ltd,BUILDER,1 BHK Apartment,"Buti Bori, Nagpur",Nagpur,14.49 L,"2,636",550,Under Construction
3,Sandesh Infrastrctures Pvt ltd,BUILDER,2 BHK Apartment,"Jamtha, Nagpur",Nagpur,22.95 L,"2,342",980,Under Construction
4,Shree Laxmi Venture,BUILDER,2 BHK Apartment,"Besa, Nagpur",Nagpur,35.31 L,"3,297",1071,Under Construction
5,Devprath Constructions LLP,BUILDER,2 BHK Apartment,"Parsodi, Nagpur",Nagpur,38.15 L,"3,500",1090,Under Construction
6,Sirsikar Developers And Builders Pvt Ltd,BUILDER,2 BHK Apartment,"Buti Bori, Nagpur",Nagpur,22 L,"2,895",760,Under Construction
7,Sandesh Infrastrctures Pvt ltd,BUILDER,3 BHK Villa,"Jamtha, Nagpur",Nagpur,49.01 L,"3,380",1450,Under Construction
8,seller,VERIFIED OWNER,2 BHK Apartment,"Jaitala, Nagpur",Nagpur,40.5 L,"4,500",900,Under Construction
9,seller,VERIFIED OWNER,2 BHK Apartment,"Adyali, Nagpur",Nagpur,67 L,"5,726",1170,Under Construction
10,seller,VERIFIED OWNER,3 BHK Apartment,"Kharbi, Nagpur",Nagpur,55 L,"3,235",1700,Ready to move
11,seller,VERIFIED OWNER,2 BHK Apartment,"Kamptee, Nagpur",Nagpur,23.14 L,"2,600",890,Under Construction
12,seller,VERIFIED OWNER,3 BHK Apartment,"Somalwada, Nagpur",Nagpur,64 L,"4,410",1451,Under Construction
13,seller,VERIFIED OWNER,2 BHK Apartment,"Zingabai Takli, Nagpur",Nagpur,27 L,"2,571",1050,Under Construction
14,seller,VERIFIED OWNER,Residential Plot,"Jamtha, Nagpur",Nagpur,37 L,"2,466",1500,Resale
15,seller,VERIFIED OWNER,Residential Plot,"Beltarodi, Nagpur",Nagpur,22.2 L,"1,850",1200,Resale
16,seller,VERIFIED OWNER,Residential Plot,"Wadi, Nagpur",Nagpur,14.28 L,"1,200",1190,Resale
17,seller,VERIFIED OWNER,2 BHK Apartment,"Somalwada, Nagpur",Nagpur,48 L,"6,857",700,Ready to move
18,seller,VERIFIED OWNER,3 BHK Apartment,"Besa, Nagpur",Nagpur,45 L,"3,214",1400,Ready to move
19,seller,VERIFIED OWNER,3 BHK Apartment,"Somalwada, Nagpur",Nagpur,64 L,"3,555",1800,Under Construction

# 1. Nagpur

In [9]:
# Extracting all Data from Makaan webside
# this Extracting 5 pages

seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

for i in range(1,6):
    urls = 'https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=' +str(i)
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=1
https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=2
https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=3
https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=4
https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?_=1669628700661&page=5

In [10]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

99
99
99
99
99
99
99
99
99

In [65]:
# Create a DataFrame

Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [66]:
df_Nagpur = pd.DataFrame(Dictionary)
df_Nagpur

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,455",1022,Under Construction
1,Devprath Constructions LLP,BUILDER,2 BHK Apartment,Parsodi,Nagpur,31.53 L,"3,500",901,Under Construction
2,Sirsikar Developers And Builders Pvt Ltd,BUILDER,1 BHK Apartment,Buti Bori,Nagpur,14.49 L,"2,636",550,Under Construction
3,Sandesh Infrastrctures Pvt ltd,BUILDER,2 BHK Apartment,Jamtha,Nagpur,22.95 L,"2,342",980,Under Construction
4,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,297",1071,Under Construction
...,...,...,...,...,...,...,...,...,...
95,Mahalakshmi Developers,AGENT,Residential Plot,Jamtha,Nagpur,19.8 L,"1,800",1100,New
96,Aman,AGENT,3 BHK Apartment,Borkhedi,Nagpur,1.55 Cr,"11,923",1300,Ready to move
97,Individual Agent,AGENT,3 BHK Independent House,Chinchbhuwan,Nagpur,60 L,"4,285",1400,Ready to move
98,Nagpur Estate,AGENT,2 BHK Apartment,Uday Nagar,Nagpur,37.5 L,"3,409",1100,Ready to move
99,Shekhar Rahangdale,AGENT,3 BHK Apartment,Somalwada,Nagpur,98 L,"7,127",1375,Ready to move

# Nagpur

In [5]:
cities = ['Nagpur', 'Pune']
seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

for i in cities:
    urls = 'https://www.makaan.com/nagpur-residential-property/buy-property-in-'+i + '-city'
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/nagpur-residential-property/buy-property-in-Nagpur-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Pune-city

In [6]:
print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

40
40
40
40
40
40
40
40
40

In [4]:
# https://www.makaan.com/nagpur-residential-property/buy-property-in-nagpur-city?page=1&_=1669744702561
# https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=3&_=1669745357667

# For multiple cities in Maharashtra

In [22]:
cities = ['Nagpur','Mumbai','Pune','Nashik','Aurangabad','Solapur','Akola','Latur','Chandrapur','Satra','Wardha','kolhapur']

seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

for i in cities:
    urls = 'https://www.makaan.com/nagpur-residential-property/buy-property-in-'+i + '-city'
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        location.append(a)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/nagpur-residential-property/buy-property-in-Nagpur-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Mumbai-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Pune-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Nashik-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Aurangabad-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Solapur-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Akola-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Latur-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Chandrapur-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Satra-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-Wardha-city
https://www.makaan.com/nagpur-residential-property/buy-property-in-kolhapur-city

In [23]:
print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

172
172
172
172
172
172
172
172
172

In [24]:
# Create a DataFrame

Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [25]:
final_df = pd.DataFrame(Dictionary)
final_df

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Shree Laxmi Venture,BUILDER,2 BHK Apartment,"Besa, Nagpur",Nagpur,35.31 L,"3,455",1022,Under Construction
1,Devprath Constructions LLP,BUILDER,2 BHK Apartment,"Parsodi, Nagpur",Nagpur,31.53 L,"3,500",901,Under Construction
2,Sirsikar Developers And Builders Pvt Ltd,BUILDER,1 BHK Apartment,"Buti Bori, Nagpur",Nagpur,14.49 L,"2,636",550,Under Construction
3,Sandesh Infrastrctures Pvt ltd,BUILDER,2 BHK Apartment,"Jamtha, Nagpur",Nagpur,22.95 L,"2,342",980,Under Construction
4,Shree Laxmi Venture,BUILDER,2 BHK Apartment,"Besa, Nagpur",Nagpur,35.31 L,"3,297",1071,Under Construction
...,...,...,...,...,...,...,...,...,...
167,Guest,OWNER,Residential Plot,"RK Nagar, Kolhapur",Kolhapur,68 L,"1,700",4000,New
168,Sameer Rahiman Shaikh,OWNER,4 BHK Independent House,"Rajopadhye Nagar, Kolhapur",Kolhapur,30 L,"3,000",1000,Ready to move
169,Surekha Patil,OWNER,Residential Plot,"Kalamba, Kolhapur",Kolhapur,30 L,"1,214",2470,Resale
170,Avinash,AGENT,2 BHK Villa,"Pratibha Nagar, Kolhapur",Kolhapur,58 L,"4,957",1170,Ready to move
171,Clear Property Consultant,AGENT,Residential Plot,"Hari Om Nagar, Kolhapur",Kolhapur,45 L,"2,614",1721,Resale

# 2.  Mumbai

In [67]:
seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []
#https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page=4&_=1669777420623

for j in range(1,6):
    urls = 'https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page='+str(j)+'&_=1669777420623'
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page=1&_=1669777420623
https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page=2&_=1669777420623
https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page=3&_=1669777420623
https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page=4&_=1669777420623
https://www.makaan.com/mumbai-residential-property/buy-property-in-mumbai-city?page=5&_=1669777420623

In [68]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

100
100
100
100
100
100
100
100
100

In [69]:
Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [70]:
df_Mumbai = pd.DataFrame(Dictionary)
df_Mumbai

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Tharwani Realty,BUILDER,1 BHK Apartment,Ambernath West,Mumbai,29.99 L,"6,533",459,Under Construction
1,Lak And Hanware Realty,BUILDER,3 BHK Apartment,Andheri West,Mumbai,2.5 Cr,"36,496",685,Ready to move
2,Romell Group,BUILDER,2 BHK Apartment,Borivali West,Mumbai,1.73 Cr,"28,360",610,Under Construction
3,MS Realty,BUILDER,2 BHK Apartment,Santacruz West,Mumbai,4.33 Cr,"56,234",770,Under Construction
4,Amar Realty,BUILDER,2 BHK Apartment,Santacruz East,Mumbai,1.8 Cr,"31,141",579,Under Construction
...,...,...,...,...,...,...,...,...,...
95,H Rishabraj Developers,BUILDER,2 BHK Apartment,Ghatkopar East,Mumbai,1.91 Cr,"30,000",639,Under Construction
96,AURUS HOMES,BUILDER,2 BHK Apartment,Taloja,Mumbai,44.44 L,"7,237",614,Ready to move
97,Precious Group,BUILDER,1 BHK Apartment,Ulhasnagar,Mumbai,29.02 L,"7,951",365,Under Construction
98,Kasturi Developers,BUILDER,1 BHK Apartment,Ulwe,Mumbai,57 L,"7,600",750,Under Construction
99,Tharwani Realty,BUILDER,3 BHK Apartment,Ambernath West,Mumbai,49 L,"5,791",846,Under Construction

# 3. Pune

In [71]:
seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

#https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=3&_=1669778518952
for j in range(1,6):
    urls = 'https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page='+str(j)+'&_=1669778518952'
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=1&_=1669778518952
https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=2&_=1669778518952
https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=3&_=1669778518952
https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=4&_=1669778518952
https://www.makaan.com/pune-residential-property/buy-property-in-pune-city?page=5&_=1669778518952

In [72]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

100
100
100
100
100
100
100
100
100

In [73]:
# for creating dataframe

Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [74]:
df_Pune = pd.DataFrame(Dictionary)
df_Pune

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Swastik Diamond Realty,BUILDER,2 BHK Apartment,Charholi Budruk,Pune,44.95 L,"6,552",686,Under Construction
1,S K Infra,BUILDER,2 BHK Apartment,Chinchwad,Pune,76.69 L,"10,652",720,Under Construction
2,Aaiji Group,BUILDER,3 BHK Apartment,Tingre Nagar,Pune,1.42 Cr,"11,442",1241,Under Construction
3,Classic Promoters and Builders,BUILDER,1 BHK Apartment,Dapodi,Pune,49 L,"9,664",507,Under Construction
4,SKYi Developers,BUILDER,2 BHK Apartment,Bhukum,Pune,44.99 L,"7,653",588,Under Construction
...,...,...,...,...,...,...,...,...,...
95,seller,VERIFIED OWNER,2 BHK Apartment,Pimple Saudagar,Pune,68 L,"7,157",950,Ready to move
96,seller,VERIFIED OWNER,3 BHK Apartment,Wakad,Pune,1.1 Cr,"7,757",1418,Ready to move
97,seller,VERIFIED OWNER,2 BHK Apartment,Dhanori,Pune,63 L,"6,200",1016,Ready to move
98,seller,VERIFIED OWNER,2 BHK Apartment,Hinjewadi,Pune,78 L,"7,282",1071,Under Construction
99,seller,VERIFIED OWNER,2 BHK Apartment,Wagholi,Pune,41.99 L,"4,665",900,Ready to move

# 4. Kolhapur

In [75]:
seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

#https://www.makaan.com/kolhapur-residential-property/buy-property-in-kolhapur-city
for j in range(1,2):
    urls = 'https://www.makaan.com/kolhapur-residential-property/buy-property-in-kolhapur-city'
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/kolhapur-residential-property/buy-property-in-kolhapur-city

In [76]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

20
20
20
20
20
20
20
20
20

In [77]:
Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [78]:
df_Kolhapur = pd.DataFrame(Dictionary)
df_Kolhapur

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,seller,VERIFIED OWNER,2 BHK Villa,Pachgaon,Kolhapur,30 L,"3,333",900,Ready to move
1,seller,VERIFIED OWNER,1 BHK Independent Floor,Laxtirth Vasahat,Kolhapur,24 L,"4,705",510,Ready to move
2,seller,VERIFIED OWNER,2 BHK Apartment,Kasaba Bawada,Kolhapur,41.46 L,"4,749",873,Ready to move
3,seller,VERIFIED OWNER,3 BHK Independent House,Rajarampuri,Kolhapur,1.2 Cr,"7,500",1600,Ready to move
4,seller,VERIFIED OWNER,3 BHK Independent House,Papachi Tikati,Kolhapur,1.3 Cr,"6,500",2000,Ready to move
5,Kedar Samangadkar,BUILDER,3 BHK Apartment,Tarabai Park,Kolhapur,95 L,"6,884",1380,Under Construction
6,seller,OWNER,2 BHK Apartment,Hari Om Nagar,Kolhapur,67 L,"5,826",1150,Ready to move
7,Shridhar,OWNER,2 BHK Apartment,Shahupuri,Kolhapur,42 L,"4,154",1011,Ready to move
8,seller,OWNER,2 BHK Independent House,Pachgaon,Kolhapur,30 L,"3,333",900,Ready to move
9,Sameer Rahiman Shaikh,OWNER,4 BHK Independent House,Rajopadhye Nagar,Kolhapur,30 L,"3,000",1000,Ready to move
10,seller,OWNER,2 BHK Independent House,Kagal,Kolhapur,27 L,"3,103",870,Under Construction
11,SACHIN B PATIL,OWNER,3 BHK Independent House,Pachgaon,Kolhapur,55 L,"5,945",925,Under Construction
12,unique proparty,AGENT,2 BHK Apartment,Shivaji Park,Kolhapur,65 L,"5,000",1300,Ready to move
13,Sanjay Sanglikar,OWNER,2 BHK Apartment,Nagala Park,Kolhapur,35 L,"3,181",1100,Ready to move
14,raghavendra murthy,OWNER,Residential Plot,Kalamba,Kolhapur,31 L,"1,823",1700,Resale
15,Guest,OWNER,Residential Plot,RK Nagar,Kolhapur,68 L,"1,700",4000,New
16,Sameer Rahiman Shaikh,OWNER,4 BHK Independent House,Rajopadhye Nagar,Kolhapur,30 L,"3,000",1000,Ready to move
17,Surekha Patil,OWNER,Residential Plot,Kalamba,Kolhapur,30 L,"1,214",2470,Resale
18,Avinash,AGENT,2 BHK Villa,Pratibha Nagar,Kolhapur,58 L,"4,957",1170,Ready to move
19,Clear Property Consultant,AGENT,Residential Plot,Hari Om Nagar,Kolhapur,45 L,"2,614",1721,Resale

# 5. Nashik

In [79]:
seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

#https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page=3
for j in range(1,6):
    urls = 'https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page='+str(j)
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page=1
https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page=2
https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page=3
https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page=4
https://www.makaan.com/nashik-residential-property/buy-property-in-nashik-city?page=5

In [80]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

100
100
100
100
100
100
100
100
100

In [81]:
Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [82]:
df_Nashik = pd.DataFrame(Dictionary)
df_Nashik

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Vaishnav Constructions,BUILDER,3 BHK Apartment,Gangapur,Nashik,95.15 L,"5,149",1848,Under Construction
1,Shreeji Group,BUILDER,4 BHK Apartment,Govind Nagar,Nashik,1.34 Cr,"6,250",2144,Under Construction
2,Jaikumar Constructions Ltd,BUILDER,3 BHK Apartment,Chandshi,Nashik,85.1 L,"5,400",1576,Under Construction
3,Rohan Enterprises,BUILDER,2 BHK Apartment,Indira Nagar,Nashik,39.1 L,"4,035",969,Under Construction
4,Arihant Builders And Developers,BUILDER,2 BHK Apartment,Chehdi,Nashik,26.1 L,"3,000",870,Under Construction
...,...,...,...,...,...,...,...,...,...
95,seller,VERIFIED OWNER,1 BHK Apartment,Deolali Gaon,Nashik,16.5 L,"3,300",500,Under Construction
96,Aaradhya Properties,BUILDER,1 BHK Apartment,Gangapur,Nashik,23.52 L,"3,536",665,Under Construction
97,EXP Global India Pvt Ltd,AGENT,4 BHK Apartment,Parijat Nagar,Nashik,2.24 Cr,"8,099",2768,Under Construction
98,Mr Sumit Acharya,AGENT,3 BHK Apartment,Uttara Nagar,Nashik,70 L,"4,375",1600,Ready to move
99,Tvisha real estates,AGENT,2 BHK Apartment,Makhmalabad,Nashik,46 L,"4,423",1040,Ready to move

# 6. Aurangabad

In [83]:
seller = []
sellertype =[]
BHKs = []
location = []
City = []
Price = []
Price_per_sqft = []
Area_sqft = []
Cons_status = []

#https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page=3&_=1669788603520
for j in range(1,6):
    urls = 'https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page='+str(j)+'&_=1669788603520'
    print(urls)
    page = requests.get(urls)
    soup = BeautifulSoup(page.text)

    # 1. Seller Name
    seller_name = soup.find_all('a',class_='seller-name')
    for i in seller_name:
        a = i.text
        seller.append(a)
        
    # 2. Seller type
    seller_type = soup.find_all('div',class_='second-line')
    for i in seller_type:
        a = i.text
        sellertype.append(a)
        
    # 3. BHK
    BHK = soup.find_all('a',class_='typelink')
    for i in BHK:
        a = i.text
        BHKs.append(a)
    
    # 4. Location
    loc = soup.find_all("a",class_="loclink")
    for i in loc:
        a = i.text
        b=  a.split(',')[0]
        location.append(b)
        
    # 5. City
    city = soup.find_all("span",class_="cityName")
    for i in city:
        a = i.text
        City.append(a)
    
    # 6. Total Price
    total_price = soup.find_all("td",class_="price")
    for i in total_price:
        a = i.text
        Price.append(a)
    
    # 7. price per sqft
    price_per_sqft = soup.find_all("td",class_="lbl rate")
    for i in price_per_sqft:
        a = i.text
        b = a.replace('/ sq ft','')
        Price_per_sqft.append(b)
    
    # 8. Area in Sqft
    Area_in_sqft = soup.find_all('td',class_='size')
    for i in Area_in_sqft:
        a = i.text
        Area_sqft.append(a)
        
    # 9. Construction status
    cons_stus = soup.find_all('td',class_='val')
    for i in cons_stus :
        a = i.text
        Cons_status.append(a)

https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page=1&_=1669788603520
https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page=2&_=1669788603520
https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page=3&_=1669788603520
https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page=4&_=1669788603520
https://www.makaan.com/aurangabad-residential-property/buy-property-in-aurangabad-city?page=5&_=1669788603520

In [84]:
# for checking length of columns

print(len(seller))
print(len(sellertype))
print(len(BHKs))
print(len(location))
print(len(City))
print(len(Price))
print(len(Price_per_sqft))
print(len(Area_sqft))
print(len(Cons_status))

68
68
68
68
68
68
68
68
68

In [85]:
Dictionary = {
    
    'Seller Name' : seller,
    'Seller type' : sellertype,
    'BHK' : BHKs,
    'Location' : location,
    'City' : City,
    'Total Price' : Price,
    'price per sqft' : Price_per_sqft,
    'Area_sqft' : Area_sqft,
    'Construction status' : Cons_status
}

In [86]:
df_Aurangabad = pd.DataFrame(Dictionary)
df_Aurangabad

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,seller,VERIFIED OWNER,5 BHK Independent House,Sangram Nagar,Aurangabad,80 L,"2,666",3000,Ready to move
1,seller,VERIFIED OWNER,2 BHK Apartment,Ulkanagari,Aurangabad,52.5 L,"6,505",807,Ready to move
2,seller,VERIFIED OWNER,3 BHK Apartment,Usmanpura,Aurangabad,92 L,"6,666",1380,Ready to move
3,seller,VERIFIED OWNER,2 BHK Apartment,Satara Parisar,Aurangabad,33.5 L,"3,045",1100,Under Construction
4,seller,VERIFIED OWNER,3 BHK Independent House,Beed Bypass Padegaon,Aurangabad,48.99 L,"3,629",1350,Ready to move
...,...,...,...,...,...,...,...,...,...
63,user6805,OWNER,1 BHK Villa,Shendra MIDC,Aurangabad,18.9 L,"3,150",600,Under Construction
64,Gandhi Rajput,OWNER,Residential Plot,Harsul,Aurangabad,5.55 L,462,1200,Resale
65,shivaji patil,OWNER,Residential Plot,Shendra MIDC,Aurangabad,5 L,"1,562",320,Resale
66,Sanket Jagdale,OWNER,1 BHK Independent House,Farola,Aurangabad,12 L,"2,000",600,Ready to move
67,A to Z Consultancy,AGENT,3 BHK Villa,Beed Bypass Road,Aurangabad,1.8 Cr,"6,617",2720,Ready to move

In [87]:
# Concatinate all cities in DataFrame

cities = pd.concat([df_Nagpur, df_Mumbai, df_Pune, df_Kolhapur, df_Nashik, df_Aurangabad ],axis=0)
cities

,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,455",1022,Under Construction
1,Devprath Constructions LLP,BUILDER,2 BHK Apartment,Parsodi,Nagpur,31.53 L,"3,500",901,Under Construction
2,Sirsikar Developers And Builders Pvt Ltd,BUILDER,1 BHK Apartment,Buti Bori,Nagpur,14.49 L,"2,636",550,Under Construction
3,Sandesh Infrastrctures Pvt ltd,BUILDER,2 BHK Apartment,Jamtha,Nagpur,22.95 L,"2,342",980,Under Construction
4,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,297",1071,Under Construction
...,...,...,...,...,...,...,...,...,...
63,user6805,OWNER,1 BHK Villa,Shendra MIDC,Aurangabad,18.9 L,"3,150",600,Under Construction
64,Gandhi Rajput,OWNER,Residential Plot,Harsul,Aurangabad,5.55 L,462,1200,Resale
65,shivaji patil,OWNER,Residential Plot,Shendra MIDC,Aurangabad,5 L,"1,562",320,Resale
66,Sanket Jagdale,OWNER,1 BHK Independent House,Farola,Aurangabad,12 L,"2,000",600,Ready to move
67,A to Z Consultancy,AGENT,3 BHK Villa,Beed Bypass Road,Aurangabad,1.8 Cr,"6,617",2720,Ready to move

In [88]:
# for resetting index

cities.reset_index(inplace=True)
cities.drop('index',axis=1,inplace=True)

In [16]:
cities

,Unnamed: 0,Seller_Name,Seller_type,Property_type,Location,City,Total_price_in_Lakhs,Price_per_sqft,Area_sqft,Construction_status
0,0,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,455",1022,Under Construction
1,1,Devprath Constructions LLP,BUILDER,2 BHK Apartment,Parsodi,Nagpur,31.53 L,"3,500",901,Under Construction
2,2,Sirsikar Developers And Builders Pvt Ltd,BUILDER,1 BHK Apartment,Buti Bori,Nagpur,14.49 L,"2,636",550,Under Construction
3,3,Sandesh Infrastrctures Pvt ltd,BUILDER,2 BHK Apartment,Jamtha,Nagpur,22.95 L,"2,342",980,Under Construction
4,4,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,297",1071,Under Construction
...,...,...,...,...,...,...,...,...,...,...
483,483,user6805,OWNER,1 BHK Villa,Shendra MIDC,Aurangabad,18.9 L,"3,150",600,Under Construction
484,484,Gandhi Rajput,OWNER,Residential Plot,Harsul,Aurangabad,5.55 L,462,1200,Resale
485,485,shivaji patil,OWNER,Residential Plot,Shendra MIDC,Aurangabad,5 L,"1,562",320,Resale
486,486,Sanket Jagdale,OWNER,1 BHK Independent House,Farola,Aurangabad,12 L,"2,000",600,Ready to move
487,487,A to Z Consultancy,AGENT,3 BHK Villa,Beed Bypass Road,Aurangabad,1.8 Cr,"6,617",2720,Ready to move

In [90]:
# Convert DataFrame to csv file

cities.to_csv("part2_dataframe.csv")

In [91]:
# import operating system and get the current working directory

import os
os.getcwd()

'C:\\Users\\HP PC\\Data Science course\\Data Science course\\PROJECT\\project 1'

In [2]:
# read csv file

cities = pd.read_csv("C:\\Users\\HP PC\\Data Science course\\Data Science course\\PROJECT\\project 1\\part2_dataframe.csv")

In [3]:
cities.head()

,Unnamed: 0,Seller Name,Seller type,BHK,Location,City,Total Price,price per sqft,Area_sqft,Construction status
0,0,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,455",1022,Under Construction
1,1,Devprath Constructions LLP,BUILDER,2 BHK Apartment,Parsodi,Nagpur,31.53 L,"3,500",901,Under Construction
2,2,Sirsikar Developers And Builders Pvt Ltd,BUILDER,1 BHK Apartment,Buti Bori,Nagpur,14.49 L,"2,636",550,Under Construction
3,3,Sandesh Infrastrctures Pvt ltd,BUILDER,2 BHK Apartment,Jamtha,Nagpur,22.95 L,"2,342",980,Under Construction
4,4,Shree Laxmi Venture,BUILDER,2 BHK Apartment,Besa,Nagpur,35.31 L,"3,297",1071,Under Construction

In [4]:
cities.shape

(488, 10)